name: Vidiotbox
favicon: null
layout_spectrum: 0.24662
typography_spectrum: 0.2618
title: Vidiot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4aa8c1'
    - '#fafaf0'
    - '#2a1b14'
    - '#f9dd30'
    - '#be4630'
  brandStrength: 0.6005659808870405
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
