name: Vidiotbox
favicon: null
layout_spectrum: 0.51582
typography_spectrum: 0.2618
title: Vidiot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2c2c2c'
    - '#c7c7c7'
    - '#5f5f5f'
    - '#888888'
  brandStrength: 0.6005659808870405
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
