name: Vidiotbox
favicon: null
layout_spectrum: 0.73984
typography_spectrum: 0.2618
title: Vidiot
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6005659808870405
  lightness: 0.0625
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
